exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("places")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("places").insert([
        {
          id: 1,
          title: "Eco Finder",
          description: "Produtos sustentáveis para o seu dia a dia",
          images_url:
            "https://www.pitkinoutside.org/ecofinder/wp-content/uploads/2019/04/April-Ag-1.jpg",
          address: "Rua Dos Bobos, 00 - Castelão",
          state: "CE",
          city: "Fortaleza",
          phone: "(85) 99999-9999",
          hr_init: "10:00",
          hr_final: "18:00",
          opening_days: "todos os dias",
          author: "1",
          type: "3",
          create_at: new Date(Date.now()),
          update_at: new Date(Date.now()),
        },
        {
          id: 2,
          title: "EcoNel",
          description: "Coletamos todo tipo de lixo que você possa imaginar",
          images_url:
            "https://www.dm.jor.br/wp-content/uploads/2018/08/4-2-10.jpg",
          address: "Rua Dos Bobos, 00 - Castelão",
          state: "CE",
          city: "Fortaleza",
          phone: "(85) 98888-9999",
          hr_init: "10:00",
          hr_final: "18:00",
          opening_days: "seg,ter,qua,qui,sex",
          author: "1",
          type: "1",
          create_at: new Date(Date.now()),
          update_at: new Date(Date.now()),
        },
        {
          id: 3,
          title: "Passeio pelo Parque do Cocó",
          description: "Produtos sustentáveis para o seu dia a dia",
          images_url:
            "https://lh3.googleusercontent.com/proxy/C4vfVrCp13p0OpVC33ebgk6Vb6I40fDrzQKgqJdPrWgD5IDiXukIT-E5UlyZtSKZCSs7mc1OwzjZmM_j9DHB2Spqv2dCDJCp_bR31dnMvcXfGFtfEVtHuqW5ujx-3i0SKw",
          address: "Rua Cocó, 00 - Cocó",
          state: "CE",
          city: "Fortaleza",
          phone: "(85) 90000-0000",
          hr_init: "10:00",
          hr_final: "18:00",
          opening_days: "sáb",
          author: "1",
          type: "2",
          create_at: new Date(Date.now()),
          update_at: new Date(Date.now()),
        },
        {
          id: 4,
          title: "EcoLoja",
          description: "Produtos & Consciência",
          images_url:
            "https://lh3.googleusercontent.com/proxy/Pq7IpbIp6p3Q89RyaUm6xPwPyz_eWNLmCKRHIsf9O7Qi6pGxHeR8Ptj_2Vs3K7qP7deHzN9o5xyHxP5y-vRemlcO9qJcS-33dLJKzoXAROdhB_6IOVdWr6VsWLRpjRAFws_hg1dCwwPf9s4LcQkF",
          address: "Rua Dos Bobos, 00 - Castelão",
          state: "SP",
          city: "Guarulhos",
          phone: "(11) 99999-9999",
          hr_init: "08:00",
          hr_final: "18:00",
          opening_days: "todos os dias",
          author: "1",
          type: "3",
          create_at: new Date(Date.now()),
          update_at: new Date(Date.now()),
        },
        {
          id: 5,
          title: "Estação São Carlos",
          description: "Coleta de lixos eletronicos",
          images_url:
            "https://www.santiagonews.com.br/img.content/noticias/noticia11066.jpg",
          address: "Rua Dos Bobos, 00 - Castelão",
          state: "SP",
          city: "São Paulo",
          phone: "(11) 98888-9999",
          hr_init: "10:00",
          hr_final: "16:00",
          opening_days: "seg,qua,sex,sáb",
          author: "1",
          type: "1",
          create_at: new Date(Date.now()),
          update_at: new Date(Date.now()),
        },
        {
          id: 6,
          title: "Encontro das Águas",
          description: "Venha ver o encontro dos Rios Negro e Solimões",
          images_url: "",
          address: "Rua Cocó, 00 - Cocó",
          state: "AM",
          city: "Manaus",
          phone: "(11) 90000-0000",
          hr_init: "10:00",
          hr_final: "14:00",
          opening_days: "sáb,dom",
          author: "1",
          type: "2",
          create_at: new Date(Date.now()),
          update_at: new Date(Date.now()),
        },
      ]);
    });
};
